version: '3.8'

services:
  flaskapp:
    image: thanhphu2643/face_recog:latest  # Sử dụng image có sẵn thay vì build
    container_name: flaskapp
    restart: always
    expose:
      - "5000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskapp
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
